### PR TITLE
pignify and weather_data_analyzer test was ambigious. Fixed.

### PR DESCRIPTION
**Pull request by Cvikli**
Pignify could be understood like "way" if the first letter was latin stuff and the other letter would cause only an "ay". Now it has to be always the "ay" way. 

weather_data_analyzer had to be leared that increasing trends means continuously increasing. Even forbidding allowing similar values. So < instead of =<. So this way it is hard to misinterpret.

### CODE REVIEW

**Comment by svilupp** [comment]
Thanks for the PR!

> weather_data_analyzer had to be leared that increasing trends means continuously increasing. Even forbidding allowing similar values. So < instead of =<. So this way it is hard to misinterpret.

Maybe we should change the reference solution to use `<=` because that's still increasing (not-decreasing). It would be more correct than calling that "stable". Or perhaps the third option should not be "stable", but "none" (ie, no trend vs increasing and decreasing). We would need to update the tests to reflect it. WDYT?

> Pignify could be understood like "way" if the first letter was latin stuff and the other letter would cause only an "ay". Now it has to be always the "ay" way.

Maybe we should agree on some standard and then add that to the prompt. It changes the task slightly but that's okay.
Let's use the definition here: https://en.wikipedia.org/wiki/Pig_Latin (first two rules).

I would suggest adding the following to the prompt:
"If a word starts with a consonant or a consonant cluster, move it to the end and append "ay" at the end. If a word starts with a vowel, append "hay" at the end."

I chose different rules for the vowel vs consonant to make it more challenging. If we agree on this, we need to adjust the tests accordingly + add some word with consonant cluster to test that logic (eg, "string" = "ingstray").

WDYT?

**Comment by Cvikli** [comment]
> Maybe we should change the reference solution to use `<=` because that's still increasing (not-decreasing). It would be more correct than calling that "stable". Or perhaps the third option should not be "stable", but "none" (ie, no trend vs increasing and decreasing). We would need to update the tests to reflect it. WDYT?

It is great idea of course. It can be anyways, we just have to note to remove ambiguity in each case.



> Maybe we should agree on some standard and then add that to the prompt. It changes the task slightly but that's okay.
> Let's use the definition here: https://en.wikipedia.org/wiki/Pig_Latin (first two rules).

Wow I just read what you said and basically the Sonnet 3.5 knew about this too indeed!!! 
image

So actually it was the "absolute" correct answer, that it even handled the case like those. XD


> "If a word starts with a consonant or a consonant cluster, move it to the end and append "ay" at the end. If a word starts with a vowel, append "hay" at the end."

We can update the reference solution and the prompt as you suggested. We just have to make sure that everyone understand the same when they read the prompt (even the LLM-s XD ) . Maybe we could note that it is a "custom pignify where ..." (but of course this could be already trivial)



Also note that there is another 3rd rule we didn't take into consideration, so hopefully if the LLMs knows a lot about this problem then he don't apply this rule next to the other two:
image

We really have to be precise as if it realize that this 2rd rule can be mixed with the above two then it can actually still create incorrect result just by being more accurate than we would expect from a senior lazy programmer.

**Comment by svilupp** [comment]
> Maybe we could note that it is a "custom pignify where ..."

Why custom pignify? This is the "wiki" definition and we even spell out the rules. IMO that's more specific than necessary. We just have to make sure to change the words in the tests not to be the ones on Wikipedia (can be memorized, we want the logic applied to new words)

> Also note that there is another 3rd rule we didn't take into consideration, so hopefully if the LLMs knows a lot about this problem then he don't apply this rule next to the other two:

Yes, I noticed it too. That's why I proposed the following addition to the prompt:
> "If a word starts with a consonant or a consonant cluster, move it to the end and append "ay" at the end. If a word starts with a vowel, append "hay" at the end."

I think that is specific enough (you can change for way or hay. It doesn't matter as long as we specify it).

> We really have to be precise as if it realize that this 2rd rule can be mixed with the above two then it can actually still create incorrect result just by being more accurate than we would expect from a senior lazy programmer.

Also, I don't think the consonant cluster mixes / contradicts with anything - it's complementary, so we can just mention it (see above). It just needs to be added to the unit tests.

**Comment by svilupp** [comment]
> It is great idea of course. It can be anyways, we just have to note to remove ambiguity in each case.

I think we should be pragmatic. Let's specify a little bit more the problem to remove some big uncertainty, but we should  not describe the code fully in English (and all edge cases) -- that would be a useless tool, because you would write more English than the resulting code.

**Pull request closed without merging**
