### PR TITLE
add new test cases to code_generation_waitlist

### PR DESCRIPTION
**Pull request by ceferisbarov**
New test cases that shouldn't show up in the leaderboards will be kept in `code_generation_waitlist`. I have also gitignored results of benchmark runs in this folder.

### CODE REVIEW

**Comment by svilupp** [comment]
Thank you for the PR!

Based on a quick review, could you please make sure the definitions run on your computer. Ideally, run a few samples with some LLM to sense check it makes sense and is solvable but not too easy.

Eg, 

```julia
function_name = "find_mean"
fn_definition = joinpath("code_generation_waitlist",
    "statistics",
    function_name,
    "definition.toml")
d = load_definition(fn_definition)["code_generation"]

# take the reference solution to be able to run it
print(d["reference_solution"])
function find_mean(data::AbstractVector, weights::AbstractVector)
    @assert length(data)==length(weights) "Data and weights must have the same length"

    total_weight = sum(weights)
    @assert total_weight!=0 "Total weight cannot be zero"

    sum_product = sum(data .* weights)

    return sum_product / total_weight
end
```

Then you can use the code blocks in `examples/create_definition.jl` to test it out:
```julia
for example in d["examples"]
    setup_code = get(d, "examples_setup", "")
    teardown_code = get(d, "examples_teardown", "")
    code_joined = string(setup_code, "\n\n", example, "\n\n", teardown_code)
    @eval(Main, $(Meta.parseall(code_joined)))
end

# Sense check that the examples work
for unit in d["unit_tests"]
    setup_code = get(d, "examples_setup", "")
    teardown_code = get(d, "examples_teardown", "")
    code_joined = string(setup_code, "\n\n", unit, "\n\n", teardown_code)
    @eval(Main, $(Meta.parseall(code_joined)))
end
```
Or an easier alternative might be to simply run: `validate_definition(d, evaluate = true)` (you need to first sync your branch with the main, where this has been fixed).

**A few observations:**
For example, the examples in `find_mean` are not executable because 1) there is extra space in the function name, 2) they provide only one of the two arguments, 3) the first example uses some `arr` that's not defined.

In addition, it would be good to:
- separate the TESTSETS into individual UNIT TESTS. If you provide full test it either fully passes or not, if you break it down, it can give more continuous scoring to the model if they pass 3/5 unit tests etc.
- It would be good to have at least 3+ examples. I know it's highly repetitive, but try some challenging inputs that are quite sensible, eg, try mixing Integer, Int16 and/or Float, try empty array, etc.
- `examples_setup` and `unit_tests_setup` are meant for defining variables, values, data to be used across the corresponding sections (ala pytest fixtures). Currently, it defines some `text` variable despite the function is meant for handling numeric inputs. Was that the intention?

**Comment by ceferisbarov** [comment]
They did run on my computer. I must have mixed up the files. Will update the PR. Thanks. No, `text` variable was not intentional. It is a leftover from the template.

**Comment by ceferisbarov** [comment]
@svilupp Examples should run successfully now. I have also removed unnecessary fields, broken down the test sets, and added more examples.

One question: `find_mode` is supposed to throw `LoadError` if we input an empty array. I hesitate to use @test_throws because an LLM might decide to handle it differently, or simply raise a different error. How should be approach situations like this?

**Comment by svilupp** [comment]
> One question: find_mode is supposed to throw LoadError if we input an empty array. I hesitate to use @test_throws because an LLM might decide to handle it differently, or simply raise a different error. How should be approach situations like this?

Hmm, good question. I'd don't punish models for things that are not obvious (eg, which error to throw). So I'd either:
1) add it as an explicit condition to the prompt (interesting case because we don't have error handling generation covered in the tests!)
2) Catch generic `Exception` (abstract type of all errors)

Side node: I'd recommend using `ArgumentError`, not LoadError if it's an "invalid argument". I'd expect LoadError in very different situations (Eg, code loading).

Does that answer your question?

**Comment by ceferisbarov** [comment]
It does! Thanks.

I will also look at the possibility of adding exception handling as a separate category.

**Comment by svilupp** [comment]
Pushed all the evals + preliminary results! Let me know what you think

**Comment by ceferisbarov** [comment]
As we discussed internally, I removed `find_mode` to make test cases less repetitive.

**Comment by svilupp** [comment]
What would you like to do as next step?

I’m thinking:
- run the waitlists suite (to make it light but comparable)
  - for a subset of templates: injulia or juliaexpertask
  - for a subset of models for comparison: gpt35, 4t, llama3 8b?
- clean up
- prepare some report view in the docs, plots, etc
- merge
WDYT?

**Comment by ceferisbarov** [comment]
I added `llama3:8b`, `codellama:13b`, and `magicoder:7b-s-cl-q6_K`. gpt35 and 4 are already there. I also split the analysis script for local and paid models and updated the relevant images.

**Comment by svilupp** [comment]
Amazing! Thank you for the contribution!

**Pull request merged**
